name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version
        uses: denoland/setup-deno@v1
        with:
            deno-version: v1.x
      - name: Lint
        run: deno fmt --check